{% set name = "petl" %}
{% set version = "1.3.0" %}
{% set sha256 = "943a6e3211616d25ebc4dcd900ca4f96f53ccd9dbb612271a23a7efdaf3f8c00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python

test:
  requires:
    - nose
  imports:
    - petl
  commands:
    - nosetests -v petl

about:
  home: http://github.com/petl-developers/petl
  license: MIT
  license_file: LICENSE.txt
  summary: 'A Python package for extracting, transforming and loading tables of data.'
  doc_url: http://petl.readthedocs.io/
  dev_url: https://github.com/petl-developers/petl

extra:
  recipe-maintainers:
    - alimanfoo
    - timbledum
