travis:
  secure:
    BINSTAR_TOKEN: QqTKa/ZCsP3A/l9EgAFk8QV85PQmvV7EdW+IVe/J4htBAqVJMP+WFdl2sZ4CLBisifWg08tN3y0Yb478/pQDqtsIXKlWkZWcZep2N5Ysnus901+zcDh1x7VmIlxcfCFQTAO6Yycx65auh8uY6eL5OD4IWTQvMeQ6EUSx9EFesi56+LFdZStuvHBeGkYA9kDkW5uDK/uF+NIcn8XQMivG4P5joJiXv4P5Tp5/rZ1E0qunQB5Uc5LJ1qVyE2nZeIEeU/BA47kvEdEp83fRhJRDW6toiAQp1MIiUJeHfwjMNZTCMlIeQNIzRQiioSsG3kzp+VTrTId8U63EoXiVYdRIjlJy9g6YdN2mS/KijEKUTJQUCZrGh2jiLbVixyi6BdCyTuM0/wJVPC+nZ5HvM0OfqbRU84+daC/UT5F3sO6AQCbsH4tdX4M0lkU3T1jcCr3kmHTbihYI9NBpn8a4aHmRV19/5lNKwkJz9xOnJ2meVZKBZ7WFtiSNnp+rI+USiwrx8ykqA7oN1QH6U2ezuoveQ1gEAEJMVAlpCA7vQEXNNPzYML8aGcta+1UecfXkB6TumyeFMrsEJd8yv8DEqsnWcq74KrrPdukJO/zaKuM/FK1kSrXAFqCQUM70D9B30wRRfm+y/7UTQIz1ytC4IEOkIB0guYIcsvie3RKUqvBBAE0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
